#
name: Create and publish a Docker image

on:
  workflow_dispatch:
    inputs:
      imgversion:
        description: 'Docker image version'
        required: true
        type: string

# Defines two custom environment variables for the workflow. These are used for the Container registry domain, and a name for the Docker image that this workflow builds.
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: openlist-lite

# There is a single job in this workflow. It's configured to run on the latest available version of Ubuntu.
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Config
      - name: Create config-file
        env:
          CONFIG: ${{ secrets.DB_CONFIG }}
        if: ${{ env.CONFIG != '' }}
        run: |
          touch config.json
          echo "$CONFIG" >> config.json

      # Log in to the Container registry.
      - name: Log in to the Container registry
        env:
          GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
        if: ${{ env.GHCR_TOKEN != '' }}
        run: |
          echo "$GHCR_TOKEN" | docker login --username ${{ github.repository_owner }} --password-stdin ${{ env.REGISTRY }}

      # Build the image based on your repository's `Dockerfile`.
      - name: Build Docker image
        run: |
          docker build . -t ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ inputs.imgversion }} \
                         -t ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest

      # Push docker image to the Container registry.
      - name: Push Docker image
        run: |
          docker push ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ inputs.imgversion }}
          docker push ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest


